import { Item } from '../types/game';

export const ALL_ITEMS: Record<string, Item> = {
  // --- WEAPONS ---
  knife: {
    id: 'knife',
    name: 'Faca Tática M9',
    category: 'weapon',
    weaponType: 'melee',
    description: 'Lâmina afiada e silenciosa. Dano rápido e não atrai hordas.',
    weight: 0.5,
    icon: 'Sword',
    stackable: false,
    quantity: 1,
    damage: 32,
    range: 52,
    fireRate: 400,
    noiseRadius: 30,
    durability: 100,
    maxDurability: 100,
  },
  crowbar: {
    id: 'crowbar',
    name: 'Pé de Cabra de Aço',
    category: 'weapon',
    weaponType: 'melee',
    description: 'Excelente para quebrar crânios de zumbis e arrombar trincos.',
    weight: 2.2,
    icon: 'Wrench',
    stackable: false,
    quantity: 1,
    damage: 48,
    range: 64,
    fireRate: 650,
    noiseRadius: 60,
    durability: 150,
    maxDurability: 150,
  },
  spiked_bat: {
    id: 'spiked_bat',
    name: 'Taco com Pregos',
    category: 'weapon',
    weaponType: 'melee',
    description: 'Arma improvisada brutal capaz de atordoar infectados.',
    weight: 1.8,
    icon: 'Hammer',
    stackable: false,
    quantity: 1,
    damage: 55,
    range: 65,
    fireRate: 600,
    noiseRadius: 70,
    durability: 120,
    maxDurability: 120,
  },
  fire_axe: {
    id: 'fire_axe',
    name: 'Machado de Bombeiro',
    category: 'weapon',
    weaponType: 'melee',
    description: 'Golpes devastadores que eliminam zumbis comuns com um acerto.',
    weight: 3.5,
    icon: 'Axe',
    stackable: false,
    quantity: 1,
    damage: 85,
    range: 70,
    fireRate: 850,
    noiseRadius: 80,
    durability: 200,
    maxDurability: 200,
  },
  pistol_9mm: {
    id: 'pistol_9mm',
    name: 'Pistola Glock 9mm',
    category: 'weapon',
    weaponType: 'pistol',
    description: 'Pistola semiautomática confiável. Barulho considerável.',
    weight: 1.1,
    icon: 'Crosshair',
    stackable: false,
    quantity: 1,
    damage: 42,
    range: 420,
    fireRate: 280,
    clipSize: 15,
    ammoType: 'ammo_9mm',
    currentAmmo: 15,
    noiseRadius: 360,
    spread: 0.05,
    durability: 250,
    maxDurability: 250,
  },
  shotgun_12g: {
    id: 'shotgun_12g',
    name: 'Espingarda Mossberg Cal. 12',
    category: 'weapon',
    weaponType: 'shotgun',
    description: 'Dispersão letal de bagos a curta distância. Extremamente barulhenta!',
    weight: 3.8,
    icon: 'Target',
    stackable: false,
    quantity: 1,
    damage: 28, // per pellet (x6)
    pellets: 6,
    range: 280,
    fireRate: 800,
    clipSize: 6,
    ammoType: 'ammo_12g',
    currentAmmo: 6,
    noiseRadius: 550,
    spread: 0.22,
    durability: 180,
    maxDurability: 180,
  },
  hunting_rifle: {
    id: 'hunting_rifle',
    name: 'Rifle de Precisão .308',
    category: 'weapon',
    weaponType: 'rifle',
    description: 'Rifle de longo alcance com alto poder de penetração.',
    weight: 4.2,
    icon: 'Crosshair',
    stackable: false,
    quantity: 1,
    damage: 130,
    range: 600,
    fireRate: 950,
    clipSize: 5,
    ammoType: 'ammo_rifle',
    currentAmmo: 5,
    noiseRadius: 600,
    spread: 0.02,
    durability: 220,
    maxDurability: 220,
  },
  molotov: {
    id: 'molotov',
    name: 'Coquetel Molotov',
    category: 'weapon',
    weaponType: 'throwable',
    description: 'Garrafa incendiária que incinera múltiplos infectados.',
    weight: 0.8,
    icon: 'Flame',
    stackable: true,
    maxStack: 5,
    quantity: 1,
    damage: 90,
    range: 260,
    fireRate: 1000,
    noiseRadius: 180,
  },

  // --- AMMO ---
  ammo_9mm: {
    id: 'ammo_9mm',
    name: 'Munição 9mm (Caixa)',
    category: 'ammo',
    description: 'Cartuchos padrão para pistola 9mm.',
    weight: 0.25,
    icon: 'CircleDot',
    stackable: true,
    maxStack: 60,
    quantity: 15,
  },
  ammo_12g: {
    id: 'ammo_12g',
    name: 'Cartuchos Calibre 12',
    category: 'ammo',
    description: 'Cartuchos de caça pesados para espingardas.',
    weight: 0.35,
    icon: 'CircleDot',
    stackable: true,
    maxStack: 24,
    quantity: 6,
  },
  ammo_rifle: {
    id: 'ammo_rifle',
    name: 'Projéteis .308 Rifle',
    category: 'ammo',
    description: 'Munição de alta potência perfurante.',
    weight: 0.3,
    icon: 'CircleDot',
    stackable: true,
    maxStack: 20,
    quantity: 5,
  },

  // --- FOOD & WATER ---
  canned_beans: {
    id: 'canned_beans',
    name: 'Feijão Enlatado',
    category: 'food',
    description: 'Alimento nutritivo conservado. Não estraga com o tempo.',
    weight: 0.4,
    icon: 'Utensils',
    stackable: true,
    maxStack: 8,
    quantity: 1,
    foodRestore: 35,
    waterRestore: 5,
  },
  energy_bar: {
    id: 'energy_bar',
    name: 'Barra de Cereais Energética',
    category: 'food',
    description: 'Rápida e leve. Recupera fome e restaura energia instantânea.',
    weight: 0.1,
    icon: 'Zap',
    stackable: true,
    maxStack: 12,
    quantity: 1,
    foodRestore: 22,
    waterRestore: 0,
  },
  cooked_meat: {
    id: 'cooked_meat',
    name: 'Carne Grelhada',
    category: 'food',
    description: 'Alimento rico em proteínas cozido na fogueira.',
    weight: 0.5,
    icon: 'Beef',
    stackable: true,
    maxStack: 6,
    quantity: 1,
    foodRestore: 55,
    waterRestore: 10,
    healthRestore: 15,
  },
  fresh_water: {
    id: 'fresh_water',
    name: 'Garrafa de Água Mineral (500ml)',
    category: 'water',
    description: 'Água pura potável e segura contra qualquer contaminação.',
    weight: 0.5,
    icon: 'Droplet',
    stackable: true,
    maxStack: 8,
    quantity: 1,
    waterRestore: 45,
  },
  soda: {
    id: 'soda',
    name: 'Lata de Refrigerante',
    category: 'water',
    description: 'Restaura sede e um pouco de energia com açúcar.',
    weight: 0.35,
    icon: 'CupSoda',
    stackable: true,
    maxStack: 10,
    quantity: 1,
    waterRestore: 30,
    foodRestore: 10,
  },
  dirty_water: {
    id: 'dirty_water',
    name: 'Garrafa de Água Suja',
    category: 'water',
    description: 'Coletada da chuva ou canos. Deve ser fervida na fogueira antes de beber!',
    weight: 0.5,
    icon: 'Droplets',
    stackable: true,
    maxStack: 8,
    quantity: 1,
    waterRestore: 20,
    infectionHeal: -15, // causes infection
  },

  // --- MEDICAL ---
  bandage: {
    id: 'bandage',
    name: 'Bandagem Estéril',
    category: 'medical',
    description: 'Estanca sangramentos e cura ferimentos leves causados por arranhões.',
    weight: 0.1,
    icon: 'HeartHandshake',
    stackable: true,
    maxStack: 10,
    quantity: 1,
    healthRestore: 25,
  },
  medkit: {
    id: 'medkit',
    name: 'Kit de Primeiros Socorros Completo',
    category: 'medical',
    description: 'Kit cirúrgico com gaze, suturas e analgésicos fortes.',
    weight: 0.9,
    icon: 'BriefcaseMedical',
    stackable: true,
    maxStack: 4,
    quantity: 1,
    healthRestore: 70,
  },
  antibiotics: {
    id: 'antibiotics',
    name: 'Frasco de Antibióticos',
    category: 'medical',
    description: 'Vital para conter e curar a infecção zumbi no sangue antes que avance.',
    weight: 0.1,
    icon: 'Pill',
    stackable: true,
    maxStack: 8,
    quantity: 1,
    infectionHeal: 45,
    healthRestore: 10,
  },
  painkillers: {
    id: 'painkillers',
    name: 'Analgésicos Fortes',
    category: 'medical',
    description: 'Alivia dores intensas e recupera estamina instantaneamente.',
    weight: 0.05,
    icon: 'Pill',
    stackable: true,
    maxStack: 10,
    quantity: 1,
    healthRestore: 15,
  },

  // --- CRAFTING MATERIALS ---
  wood_plank: {
    id: 'wood_plank',
    name: 'Tábua de Madeira',
    category: 'material',
    description: 'Madeira resistente recolhida de móveis ou construções.',
    weight: 1.2,
    icon: 'Boxes',
    stackable: true,
    maxStack: 30,
    quantity: 1,
  },
  nails: {
    id: 'nails',
    name: 'Caixa de Pregos',
    category: 'material',
    description: 'Essencial para pregar barricadas em portas e janelas.',
    weight: 0.3,
    icon: 'Pin',
    stackable: true,
    maxStack: 50,
    quantity: 10,
  },
  scrap_metal: {
    id: 'scrap_metal',
    name: 'Sucata de Metal',
    category: 'material',
    description: 'Chapas e barras de aço para reforçar defesas e forjar armas.',
    weight: 1.5,
    icon: 'Layers',
    stackable: true,
    maxStack: 20,
    quantity: 1,
  },
  cloth: {
    id: 'cloth',
    name: 'Tecido / Retalhos',
    category: 'material',
    description: 'Pano limpo usado em curativos e coquetéis molotov.',
    weight: 0.1,
    icon: 'Shirt',
    stackable: true,
    maxStack: 30,
    quantity: 1,
  },
  duct_tape: {
    id: 'duct_tape',
    name: 'Fita Silver Tape',
    category: 'material',
    description: 'Fita adesiva ultra resistente para fixar componentes.',
    weight: 0.2,
    icon: 'Tape',
    stackable: true,
    maxStack: 10,
    quantity: 1,
  },
  alcohol: {
    id: 'alcohol',
    name: 'Garrafa de Álcool 70%',
    category: 'material',
    description: 'Desinfetante químico inflamável, essencial para molotovs.',
    weight: 0.6,
    icon: 'FlaskConical',
    stackable: true,
    maxStack: 10,
    quantity: 1,
  },
  electronics: {
    id: 'electronics',
    name: 'Componentes Eletrônicos',
    category: 'material',
    description: 'Fios, chips e baterias para iluminação e defesas avançadas.',
    weight: 0.4,
    icon: 'Cpu',
    stackable: true,
    maxStack: 20,
    quantity: 1,
  },
  car_battery: {
    id: 'car_battery',
    name: 'Bateria Automotiva 12V',
    category: 'material',
    description: 'Fonte de energia pesada retirada do capô de veículos.',
    weight: 7.0,
    icon: 'BatteryMedium',
    stackable: false,
    quantity: 1,
  },

  // --- STRUCTURES (Placed via Build Mode) ---
  barricade_wood: {
    id: 'barricade_wood',
    name: 'Barricada de Madeira',
    category: 'structure',
    structureType: 'barricade_wood',
    description: 'Bloqueia portas ou janelas. Retém o avanço dos infectados.',
    weight: 3.5,
    icon: 'Shield',
    stackable: true,
    maxStack: 10,
    quantity: 1,
  },
  barricade_metal: {
    id: 'barricade_metal',
    name: 'Barricada Reforçada de Aço',
    category: 'structure',
    structureType: 'barricade_metal',
    description: 'Defesa pesada quase impenetrável contra ataques noturnos e invasores.',
    weight: 6.0,
    icon: 'ShieldCheck',
    stackable: true,
    maxStack: 5,
    quantity: 1,
  },
  spike_trap: {
    id: 'spike_trap',
    name: 'Armadilha de Espinhos',
    category: 'structure',
    structureType: 'spike_trap',
    description: 'Espetos de madeira pontiagudos que perfuram zumbis que passarem por cima.',
    weight: 2.5,
    icon: 'AlertTriangle',
    stackable: true,
    maxStack: 8,
    quantity: 1,
  },
  storage_chest: {
    id: 'storage_chest',
    name: 'Baú de Suprimentos Seguro',
    category: 'structure',
    structureType: 'storage_chest',
    description: 'Baú trancado para estocar armas e mantimentos em sua base fortificada.',
    weight: 4.0,
    icon: 'Archive',
    stackable: true,
    maxStack: 4,
    quantity: 1,
  },
  rain_collector: {
    id: 'rain_collector',
    name: 'Coletor de Água da Chuva',
    category: 'structure',
    structureType: 'rain_collector',
    description: 'Capta e filtra água da chuva continuamente durante a partida.',
    weight: 4.5,
    icon: 'CloudRain',
    stackable: true,
    maxStack: 3,
    quantity: 1,
  },
  campfire: {
    id: 'campfire',
    name: 'Fogueira de Sobrevivência',
    category: 'structure',
    structureType: 'campfire',
    description: 'Emite calor, afasta infectados assustados e ferve água suja ou cozinha carnes.',
    weight: 3.0,
    icon: 'Flame',
    stackable: true,
    maxStack: 3,
    quantity: 1,
  },
  sleeping_bag: {
    id: 'sleeping_bag',
    name: 'Saco de Dormir / Cama',
    category: 'structure',
    structureType: 'sleeping_bag',
    description: 'Permite descansar em segurança dentro de sua base e avançar o tempo noturno.',
    weight: 2.0,
    icon: 'Moon',
    stackable: true,
    maxStack: 2,
    quantity: 1,
  },
  spotlight: {
    id: 'spotlight',
    name: 'Holofote Defensivo 12V',
    category: 'structure',
    structureType: 'spotlight',
    description: 'Ilumina o perímetro externo da base à noite, cegando corredores.',
    weight: 5.5,
    icon: 'Sun',
    stackable: true,
    maxStack: 3,
    quantity: 1,
  },
};

export function cloneItem(itemId: string, quantity = 1): Item {
  const template = ALL_ITEMS[itemId];
  if (!template) {
    throw new Error(`Item ${itemId} not found`);
  }
  return {
    ...template,
    quantity,
  };
}
