import { SkillNode } from '../types/game';

export const INITIAL_SKILLS: Record<string, SkillNode> = {
  survival: {
    id: 'survival',
    name: 'Sobrevivência & Metabolismo',
    category: 'survival',
    level: 0,
    maxLevel: 5,
    cost: 1,
    description: 'Aprenda a racionar calorias e reter líquidos vitais em situações extremas.',
    bonusText: '-10% consumo de fome e sede por nível. Nível 3 permite coletar o dobro de água da chuva.',
  },
  stealth: {
    id: 'stealth',
    name: 'Furtividade & Passos Silenciosos',
    category: 'agility',
    level: 0,
    maxLevel: 5,
    cost: 1,
    description: 'Movimente-se como uma sombra entre os escombros da cidade sem chamar a atenção dos mortos.',
    bonusText: '-12% no raio de som ao caminhar e revistar por nível. Zumbis demoram mais para notar sua presença.',
  },
  athletics: {
    id: 'athletics',
    name: 'Atletismo & Vigor Físico',
    category: 'agility',
    level: 0,
    maxLevel: 5,
    cost: 1,
    description: 'Aprimora o condicionamento cardiovascular e a capacidade de carga.',
    bonusText: '+15 estamina máxima e +5% velocidade de corrida por nível. +3kg na capacidade do inventário.',
  },
  combat: {
    id: 'combat',
    name: 'Balística & Armas de Fogo',
    category: 'combat',
    level: 0,
    maxLevel: 5,
    cost: 1,
    description: 'Manejo tático de pistolas, espingardas e fuzis de assalto.',
    bonusText: '+10% dano de projéteis e -15% tempo de recarga por nível.',
  },
  melee: {
    id: 'melee',
    name: 'Combate Brutal Corpo a Corpo',
    category: 'combat',
    level: 0,
    maxLevel: 5,
    cost: 1,
    description: 'Técnicas de combate com machados, tacos com pregos, pés de cabra e lâminas.',
    bonusText: '+15% dano com armas brancas e +5% chance de golpe crítico (dano duplo). Menos estamina gasta.',
  },
  engineering: {
    id: 'engineering',
    name: 'Engenharia & Fortificação',
    category: 'crafting',
    level: 0,
    maxLevel: 5,
    cost: 1,
    description: 'Habilidade para erguer barricadas fortificadas, armadilhas e defesas para repelir a noite.',
    bonusText: '+20% vida máxima para barricadas e estruturas por nível. Permite fabricar holofotes e defesas de metal.',
  },
  medicine: {
    id: 'medicine',
    name: 'Primeiros Socorros & Imunidade',
    category: 'survival',
    level: 0,
    maxLevel: 5,
    cost: 1,
    description: 'Conhecimento médico para tratar lacerações e resistir ao vírus zumbi.',
    bonusText: '+15% de cura em todos os itens médicos. Resistência natural à infecção +10% por nível.',
  },
};
